spring:
  application:
    name: port_pulse

  datasource:
    url: jdbc:postgresql://localhost:5432/portpulse
    username: port5432
    password: portpulse1992
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  lever:
    root: INFO
    com.portpulse: DEBUG
  file:
    name: logs/portpulse.log

server:
  port: 8081

portpulse:
  pipeline:
    python-path: pipeline/.venv/Scripts/python.exe
    working-dir: pipeline
    schedule-cron: "0 30 6 * * *"
